apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixfrontend-catalog
  labels:
    app: netflixfrontend-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflixfrontend-catalog
  template:
    metadata:
        labels:
          app: netflixfrontend-catalog
    spec:
      containers:
      - name: server
        image: davidhei/NetflixFrontend:catalog-v0.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: netflixfrontend-catalog-service
spec:
  selector:
    app: netflixfrontend-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080