apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixfrontend-frontend
  labels:
    app: netflixfrontend-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflixfrontend-frontend
  template:
    metadata:
        labels:
          app: netflixfrontend-frontend
    spec:
      containers:
      - name: server
        image: yaeli1/netflixfrontend:0.0.15
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: http://netflix-catalog-service:8080
          - name: REDIS_URL
            value: redis-service:6379