apiVersion: apps/v1
kind: Deployment
metadata:
  name: NetflixFrontend-frontend
  labels:
    app: NetflixFrontend-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NetflixFrontend-frontend
  template:
    metadata:
        labels:
          app: NetflixFrontend-frontend
    spec:
      containers:
      - name: server
        image: davidhei/NetflixFrontend:frontend-v0.0.3
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: http://netflix-catalog-service:8080
          - name: REDIS_URL
            value: redis-service:6379
---
apiVersion: v1
kind: Service
metadata:
  name: netflixfrontend-frontend-service
spec:
  selector:
    app: NetflixFrontend-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
